GET http://laravel_9_dev.local/api/v1/faq/questions-answers/answer/1
Accept: application/json

###
GET http://laravel_9_dev.local/api/v1/faq/questions-answers
Accept: application/json

###
GET http://laravel_9_dev.local/api/v1/faq/questions-answers/questions/10
Accept: application/json

###



